version: '3.6'
services:
  mailhog:
    image: mailhog/mailhog
    ports:
    - "8025:8025"
    networks: 
    - demo-network
  keycloak:
    image: jboss/keycloak:latest
    ports:
    - "28080:8080"
    networks: 
    - demo-network
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
  postgres:
    image: postgres:12
    # restart: always
    networks: 
    - demo-network
    volumes:
    - postgres_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-beta.1
    ports:
    - "18080:8080"
    depends_on:
    - "postgres"
    networks: 
    - demo-network
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_JWT_SECRET: "{\"jwk_url\":\"http://keycloak:8080/auth/realms/hasura/protocol/openid-connect/certs\"}"
volumes:
  postgres_db_data:
networks:
  demo-network:
